// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJtpiuZ0P4VcKF591qzddZ_Nde2aAems8',
    appId: '1:462592756005:web:1a9e1271c2e4e8c46d32cc',
    messagingSenderId: '462592756005',
    projectId: 'xpersonaa-61f4f',
    authDomain: 'xpersonaa-61f4f.firebaseapp.com',
    storageBucket: 'xpersonaa-61f4f.firebasestorage.app',
    measurementId: 'G-P62V0V1W9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkvImOx9gvJ-6HkFMkKAvqyR6h9km__lc',
    appId: '1:462592756005:android:a126cc28fb939f826d32cc',
    messagingSenderId: '462592756005',
    projectId: 'xpersonaa-61f4f',
    storageBucket: 'xpersonaa-61f4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi8xRZpoIAL6XF0Z5-YJYomrVTlP2tTT4',
    appId: '1:462592756005:ios:645246759fe133ad6d32cc',
    messagingSenderId: '462592756005',
    projectId: 'xpersonaa-61f4f',
    storageBucket: 'xpersonaa-61f4f.firebasestorage.app',
    iosBundleId: 'com.sycodes.xpersonaa',
  );
}
